# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy
  
# Language & Timezone
lang: en
timezone: Africa/Tunis

# SEO settings
title: ampls
tagline: "Cybersecurity Insights & Reports"
description: >-
  A personal site dedicated to cybersecurity writeups, tutorials, and reports by Garaali Mohamed Amine.

url: "https://ampls-911.github.io"

github:
  username: "ampls-911"

social:
  name: "Garaali Mohamed Amine"
  email: "Garaaliamine@proton.me"
  links:
    - https://www.linkedin.com/in/mohamed-amine-garaali-aa49a6350
    - https://github.com/ampls-911

# Theme & appearance
theme_mode: dark
cdn: "https://chirpy-img.netlify.app"
avatar: "https://raw.githubusercontent.com/ampls-911/ampls-911.github.io/master/assets/ampls.jpg"
social_preview_image: 

# Global site options
toc: true

# Comments system disabled
comments:
  provider:

# Self-hosted assets (disabled)
assets:
  self_host:
    enabled: false

# PWA (installable app)
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: []

# Pagination
paginate: 10
baseurl: ""

# Markdown & code settings
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
